"""add correction action

Revision ID: 11cedb4d7100
Revises: c57871b256fe
Create Date: 2026-04-23 14:59:05.965810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cedb4d7100'
down_revision: Union[str, None] = 'c57871b256fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correction_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True, comment='ID назначенного исполнителя'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание конкретного действия'),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='correctionactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата создания действия'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True, comment='Дата назначения исполнителю'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата фактического завершения'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['correction_id'], ['corrections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_actions_assigned_user_id'), 'correction_actions', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_correction_actions_correction_id'), 'correction_actions', ['correction_id'], unique=False)
    op.create_index(op.f('ix_correction_actions_document_id'), 'correction_actions', ['document_id'], unique=False)
    op.create_index(op.f('ix_correction_actions_id'), 'correction_actions', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_correction_actions_id'), table_name='correction_actions')
    op.drop_index(op.f('ix_correction_actions_document_id'), table_name='correction_actions')
    op.drop_index(op.f('ix_correction_actions_correction_id'), table_name='correction_actions')
    op.drop_index(op.f('ix_correction_actions_assigned_user_id'), table_name='correction_actions')
    op.drop_table('correction_actions')
    # ### end Alembic commands ###
