"""add original_filename to attachments

Revision ID: 21b16cc52987
Revises: 58c724293e22
Create Date: 2026-04-13 16:24:47.433441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b16cc52987'
down_revision: Union[str, None] = '58c724293e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_attachments', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('message_attachments', sa.Column('original_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_attachments', 'original_filename')
    op.drop_column('document_attachments', 'original_filename')
    # ### end Alembic commands ###
