"""add analysis_required to problem_action_enum

Revision ID: 34f56d00b896
Revises: 4a9f55b64932
Create Date: 2026-04-15 16:20:15.815167

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '34f56d00b896'
down_revision: Union[str, None] = '4a9f55b64932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Добавляем значение только если его ещё нет (PostgreSQL 12+)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_enum 
                WHERE enumlabel = 'analysis_required' 
                AND enumtypid = 'problem_action_enum'::regtype
            ) THEN
                ALTER TYPE problem_action_enum ADD VALUE 'analysis_required';
            END IF;
        END $$;
    """)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
