"""correction changes

Revision ID: 3b69671e9315
Revises: ff84ff6d76ec
Create Date: 2026-04-29 15:50:28.990455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b69671e9315'
down_revision: Union[str, None] = 'ff84ff6d76ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('target_document_id', sa.Integer(), nullable=True, comment='Документ, на который назначена коррекция'))
    op.alter_column('corrections', 'document_id',
               existing_type=sa.INTEGER(),
               comment='Исходный документ (по которому выявлено отклонение)',
               existing_nullable=False)
    op.alter_column('corrections', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Создатель коррекции',
               existing_nullable=False)
    op.alter_column('corrections', 'completed_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Исполнитель (завершил)',
               existing_nullable=True)
    op.alter_column('corrections', 'verified_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Верификатор',
               existing_nullable=True)
    op.drop_index(op.f('ix_corrections_problem_registration_id'), table_name='corrections')
    op.create_index(op.f('ix_corrections_target_document_id'), 'corrections', ['target_document_id'], unique=False)
    op.drop_constraint(op.f('corrections_problem_registration_id_fkey'), 'corrections', type_='foreignkey')
    op.create_foreign_key(None, 'corrections', 'documents', ['target_document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('corrections', 'problem_registration_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('problem_registration_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'corrections', type_='foreignkey')
    op.create_foreign_key(op.f('corrections_problem_registration_id_fkey'), 'corrections', 'problem_registrations', ['problem_registration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_corrections_target_document_id'), table_name='corrections')
    op.create_index(op.f('ix_corrections_problem_registration_id'), 'corrections', ['problem_registration_id'], unique=False)
    op.alter_column('corrections', 'verified_by',
               existing_type=sa.INTEGER(),
               comment='Верификатор',
               existing_nullable=True)
    op.alter_column('corrections', 'completed_by',
               existing_type=sa.INTEGER(),
               comment='Исполнитель (завершил)',
               existing_nullable=True)
    op.alter_column('corrections', 'created_by',
               existing_type=sa.INTEGER(),
               comment='Создатель коррекции',
               existing_nullable=False)
    op.alter_column('corrections', 'document_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Исходный документ (по которому выявлено отклонение)',
               existing_nullable=False)
    op.drop_column('corrections', 'target_document_id')
    # ### end Alembic commands ###
