"""create problem_registration

Revision ID: 4a9f55b64932
Revises: 7ff2f83e7a5f
Create Date: 2026-04-15 15:58:04.653660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9f55b64932'
down_revision: Union[str, None] = '7ff2f83e7a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nomenclature', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Дата утверждения'),
    # 👇 ИСПРАВЛЕНО: значения enum приведены к нижнему регистру (как в вашей модели)
    # 👇 ИСПРАВЛЕННАЯ строка с action:
    sa.Column(
        'action', 
        sa.Enum(
            'undefined', 'rejected', 'closed', 'analysis_required', 'assign_executor', 
            name='problem_action_enum', 
            create_type=False,  # 👈 КЛЮЧЕВОЕ: не пытаться создавать ENUM, он уже есть
            create_constraint=True
        ), 
        server_default=sa.text("'analysis_required'"), 
        nullable=True, 
        comment='Действие по проблеме'
    ),
    sa.Column('responsible_department_id', sa.Integer(), nullable=True, comment='ID ответственного отделения'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий к проблеме'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_problem_registrations_id'), 'problem_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_registrations_id'), table_name='problem_registrations')
    op.drop_table('problem_registrations')
    # ### end Alembic commands ###
