"""rename clearances to permissions in user_profiles

Revision ID: 4ed7bec763d8
Revises: 77363632dc26
Create Date: 2026-04-06 15:34:12.422620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed7bec763d8'
down_revision: Union[str, None] = '77363632dc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('permissions', sa.String(length=255), nullable=True))
    op.drop_column('user_profiles', 'clearances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('clearances', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'permissions')
    # ### end Alembic commands ###
