"""update document model with number, status_id, current_stage

Revision ID: 60054073933b
Revises: 6683db3db0da
Create Date: 2026-04-06 14:43:50.430512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60054073933b'
down_revision: Union[str, None] = '6683db3db0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('number', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('status_id', sa.Integer(), nullable=True))
    # Создаём ENUM тип вручную
    documentstage_enum = sa.Enum('NEW', 'IN_PROGRESS', 'WAITING', 'CLOSED', name='documentstage')
    documentstage_enum.create(op.get_bind())
    op.add_column('documents', sa.Column('current_stage', documentstage_enum, nullable=False))
    op.create_index(op.f('ix_documents_number'), 'documents', ['number'], unique=True)
    op.drop_constraint(op.f('documents_creator_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'creator_id')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('doc_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_creator_id_fkey'), 'documents', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documents_number'), table_name='documents')
    op.drop_column('documents', 'current_stage')
    op.drop_column('documents', 'status_id')
    op.drop_column('documents', 'created_by')
    op.drop_column('documents', 'number')
    # Удаляем ENUM тип
    documentstage_enum = sa.Enum(name='documentstage')
    documentstage_enum.drop(op.get_bind())
    # ### end Alembic commands ###
