"""change_permissions_to_json2

Revision ID: 64731e5a96b5
Revises: 257cb2247f01
Create Date: 2026-04-30 16:10:54.076288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64731e5a96b5'
down_revision: Union[str, None] = '257cb2247f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('user_profiles', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('user_profiles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###
