"""change nomenclature_id to nomenclature string

Revision ID: 65cff0d7ca39
Revises: 5bded3cee994
Create Date: 2026-04-06 15:07:46.201286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cff0d7ca39'
down_revision: Union[str, None] = '5bded3cee994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_registrations', sa.Column('nomenclature', sa.String(length=100), nullable=True))
    op.drop_column('problem_registrations', 'nomenclature_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_registrations', sa.Column('nomenclature_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('problem_registrations', 'nomenclature')
    # ### end Alembic commands ###
