"""add document fields is_locked is_archived is_anonymized language priority

Revision ID: 6efaf58d67cc
Revises: 7bee5277b167
Create Date: 2026-04-10 11:33:56.640276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efaf58d67cc'
down_revision: Union[str, None] = '7bee5277b167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала создаём ENUM типы
    documentlanguage = sa.Enum('RU', 'EN', name='documentlanguage')
    documentlanguage.create(op.get_bind())

    documentpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='documentpriority')
    documentpriority.create(op.get_bind())

    # Добавляем колонки
    op.add_column('documents', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('is_anonymized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('language', documentlanguage, server_default='RU', nullable=True))
    op.add_column('documents', sa.Column('priority', documentpriority, server_default='MEDIUM', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'priority')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'is_anonymized')
    op.drop_column('documents', 'is_archived')
    op.drop_column('documents', 'is_locked')

    # Удаляем ENUM типы
    sa.Enum(name='documentpriority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='documentlanguage').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
