"""add action_execution table

Revision ID: 77363632dc26
Revises: 705bd6df58a1
Create Date: 2026-04-06 15:14:57.585152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77363632dc26'
down_revision: Union[str, None] = '705bd6df58a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corrective_action_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corrective_action_id'], ['corrective_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corrective_action_id')
    )
    op.create_index(op.f('ix_action_executions_id'), 'action_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_executions_id'), table_name='action_executions')
    op.drop_table('action_executions')
    # ### end Alembic commands ###
