"""add uploaded_by

Revision ID: 7b5d207de981
Revises: b918f9088645
Create Date: 2026-04-29 14:38:51.361912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5d207de981'
down_revision: Union[str, None] = 'b918f9088645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_attachments', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message_attachments', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_attachments', type_='foreignkey')
    op.drop_column('message_attachments', 'uploaded_by')
    # ### end Alembic commands ###
