"""add is_archived and is_closed to chats

Revision ID: 7bee5277b167
Revises: c3a6d5825fac
Create Date: 2026-04-10 11:17:06.562105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bee5277b167'
down_revision: Union[str, None] = 'c3a6d5825fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_archived', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('chats', sa.Column('is_closed', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_closed')
    op.drop_column('chats', 'is_archived')
    # ### end Alembic commands ###
