"""add is_deleted soft delete to attachments

Revision ID: 94a4d73a32b9
Revises: 21b16cc52987
Create Date: 2026-04-13 16:36:54.577778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a4d73a32b9'
down_revision: Union[str, None] = '21b16cc52987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_attachments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('message_attachments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_attachments', 'is_deleted')
    op.drop_column('document_attachments', 'is_deleted')
    # ### end Alembic commands ###
