"""add is_anonymized to chats

Revision ID: 96212d0a50d0
Revises: a98c6f7de99c
Create Date: 2026-04-10 14:54:24.076129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96212d0a50d0'
down_revision: Union[str, None] = 'a98c6f7de99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_anonymized', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_anonymized')
    # ### end Alembic commands ###
