"""chenge ca

Revision ID: 9946f60fa320
Revises: 11cedb4d7100
Create Date: 2026-04-23 15:12:26.173124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9946f60fa320'
down_revision: Union[str, None] = '11cedb4d7100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correction_actions', sa.Column('comment', sa.Text(), nullable=True, comment='Дополнительный комментарий к выполнению или отклонению'))
    op.alter_column('correction_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='Дата создания действия',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correction_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='Дата создания действия',
               existing_server_default=sa.text('now()'))
    op.drop_column('correction_actions', 'comment')
    # ### end Alembic commands ###
