"""replace status_id with status enum

Revision ID: a98c6f7de99c
Revises: af18b294f3ac
Create Date: 2026-04-10 12:21:28.629740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98c6f7de99c'
down_revision: Union[str, None] = 'af18b294f3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаём ENUM тип
    documentstatus = sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING', 'CLOSED', 'REJECTED', name='documentstatus')
    documentstatus.create(op.get_bind())

    # Удаляем FK и колонку status_id
    op.drop_constraint(op.f('documents_status_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'status_id')

    # Добавляем новую колонку status
    op.add_column('documents', sa.Column('status', documentstatus, server_default='OPEN', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')

    # Возвращаем status_id
    op.add_column('documents', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_status_id_fkey'), 'documents', 'statuses', ['status_id'], ['id'], ondelete='SET NULL')

    # Удаляем ENUM тип
    sa.Enum(name='documentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
