"""add assigned_to to documents

Revision ID: af18b294f3ac
Revises: 6efaf58d67cc
Create Date: 2026-04-10 12:14:07.772613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af18b294f3ac'
down_revision: Union[str, None] = '6efaf58d67cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'assigned_to')
    # ### end Alembic commands ###
