"""empty message

Revision ID: b918f9088645
Revises: 6bb2f9e273e9
Create Date: 2026-04-27 10:37:25.200204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b918f9088645'
down_revision: Union[str, None] = '6bb2f9e273e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correction_actions', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', name='correctionactionstatus'),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correction_actions', 'status',
               existing_type=sa.String(length=15),
               type_=postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', name='correctionactionstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
