"""энам из юзера убран

Revision ID: c19488d86f01
Revises: a2dab2cd4c3a
Create Date: 2026-04-27 09:41:22.461582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c19488d86f01'
down_revision: Union[str, None] = 'a2dab2cd4c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. status: ENUM('OPEN', ...) → String(20)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'WAITING', 'CLOSED', 'REJECTED', name='documentstatus'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'OPEN'::documentstatus"),
               postgresql_using="status::text")  # ✅ Явно приводим к тексту

    # 2. current_stage: ENUM('NEW', ...) → Integer ⚠️ ТРЕБУЕТ МАППИНГА
    op.alter_column('documents', 'current_stage',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'WAITING', 'CLOSED', name='documentstage'),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="""
                   CASE current_stage::text
                       WHEN 'NEW' THEN 1
                       WHEN 'IN_PROGRESS' THEN 2
                       WHEN 'WAITING' THEN 3
                       WHEN 'CLOSED' THEN 4
                       ELSE 1  -- fallback на случай некорректных данных
                   END
               """)  # ✅ CASE-маппинг строка → число

    # 3. language: ENUM('RU', 'EN') → String(2)
    op.alter_column('documents', 'language',
               existing_type=postgresql.ENUM('RU', 'EN', name='documentlanguage'),
               type_=sa.String(length=2),
               existing_nullable=True,
               existing_server_default=sa.text("'RU'::documentlanguage"),
               postgresql_using="language::text")

    # 4. priority: ENUM('LOW', ...) → String(10)
    op.alter_column('documents', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='documentpriority'),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'MEDIUM'::documentpriority"),
               postgresql_using="priority::text")


def downgrade() -> None:
    # Обратная миграция: Integer → ENUM для current_stage
    op.alter_column('documents', 'current_stage',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'WAITING', 'CLOSED', name='documentstage'),
               existing_nullable=False,
               postgresql_using="""
                   CASE current_stage
                       WHEN 1 THEN 'NEW'
                       WHEN 2 THEN 'IN_PROGRESS'
                       WHEN 3 THEN 'WAITING'
                       WHEN 4 THEN 'CLOSED'
                       ELSE 'NEW'
                   END::documentstage
               """)

    # Остальные поля: String → ENUM
    op.alter_column('documents', 'priority',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='documentpriority'),
               existing_nullable=True,
               existing_server_default=sa.text("'MEDIUM'::documentpriority"),
               postgresql_using="priority::documentpriority")

    op.alter_column('documents', 'language',
               existing_type=sa.String(length=2),
               type_=postgresql.ENUM('RU', 'EN', name='documentlanguage'),
               existing_nullable=True,
               existing_server_default=sa.text("'RU'::documentlanguage"),
               postgresql_using="language::documentlanguage")

    op.alter_column('documents', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'WAITING', 'CLOSED', 'REJECTED', name='documentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'OPEN'::documentstatus"),
               postgresql_using="status::documentstatus")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'priority',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='documentpriority'),
               existing_nullable=True,
               existing_server_default=sa.text("'MEDIUM'::documentpriority"))
    op.alter_column('documents', 'language',
               existing_type=sa.String(length=2),
               type_=postgresql.ENUM('RU', 'EN', name='documentlanguage'),
               existing_nullable=True,
               existing_server_default=sa.text("'RU'::documentlanguage"))
    op.alter_column('documents', 'current_stage',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'WAITING', 'CLOSED', name='documentstage'),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'WAITING', 'CLOSED', 'REJECTED', name='documentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'OPEN'::documentstatus"))
    # ### end Alembic commands ###
