"""add subject to problem_registration

Revision ID: c3a6d5825fac
Revises: d05e9b16f4b5
Create Date: 2026-04-10 09:40:31.230783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a6d5825fac'
down_revision: Union[str, None] = 'd05e9b16f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_registrations', sa.Column('subject', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_registrations', 'subject')
    # ### end Alembic commands ###
