"""remove is_deleted from corrections

Revision ID: c57871b256fe
Revises: f5e7e29434d0
Create Date: 2026-04-23 10:43:12.256304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57871b256fe'
down_revision: Union[str, None] = 'f5e7e29434d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_root_causes_id'), table_name='root_causes')
    op.drop_table('root_causes')
    op.alter_column('corrections', 'title',
                existing_type=sa.VARCHAR(length=200),
                comment='Краткое название корректирующего действия',
                existing_nullable=False)
    op.alter_column('corrections', 'description',
                existing_type=sa.TEXT(),
                comment='Описание отклонения/проблемы',
                existing_nullable=True)
    op.alter_column('corrections', 'corrective_action',
                existing_type=sa.TEXT(),
                comment='Фактически выполненные действия',
                existing_nullable=False)
    op.alter_column('corrections', 'planned_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment='Плановый срок выполнения',
            existing_nullable=True)
    op.alter_column('corrections', 'completed_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment='Фактическая дата выполнения',
            existing_nullable=True)
    op.alter_column('corrections', 'created_by',
            existing_type=sa.INTEGER(),
            comment='Создатель коррекции',
            existing_nullable=False)
    op.alter_column('corrections', 'completed_by',
            existing_type=sa.INTEGER(),
            comment='Исполнитель (завершил)',
            existing_nullable=True)
    op.alter_column('corrections', 'verified_by',
            existing_type=sa.INTEGER(),
            comment='Верификатор',
            existing_nullable=True)
    op.drop_index(op.f('ix_corrections_problem_registration_id'), table_name='corrections')
    op.create_index(op.f('ix_corrections_problem_registration_id'), 'corrections', ['problem_registration_id'], unique=False)
    op.drop_column('corrections', 'is_deleted')
    op.alter_column('document_attachments', 'file_type',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=255),
            existing_nullable=True)
    op.alter_column('problem_registrations', 'action',
            existing_type=postgresql.ENUM('UNDEFINED', 'REJECTED', 'CLOSED', 'ANALYSIS_REQUIRED', 'ASSIGN_EXEC', name='problem_action_enum'),
            nullable=True,
            comment='Действие по проблеме',
            existing_server_default=sa.text("'UNDEFINED'::problem_action_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_registrations', 'action',
            existing_type=postgresql.ENUM('UNDEFINED', 'REJECTED', 'CLOSED', 'ANALYSIS_REQUIRED', 'ASSIGN_EXEC', name='problem_action_enum'),
            nullable=False,
            comment=None,
            existing_comment='Действие по проблеме',
            existing_server_default=sa.text("'UNDEFINED'::problem_action_enum"))
    op.alter_column('document_attachments', 'file_type',
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True)
    op.add_column('corrections', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_corrections_problem_registration_id'), table_name='corrections')
    op.create_index(op.f('ix_corrections_problem_registration_id'), 'corrections', ['problem_registration_id'], unique=False)
    op.alter_column('corrections', 'verified_by',
            existing_type=sa.INTEGER(),
            comment=None,
            existing_comment='Верификатор',
            existing_nullable=True)
    op.alter_column('corrections', 'completed_by',
            existing_type=sa.INTEGER(),
            comment=None,
            existing_comment='Исполнитель (завершил)',
            existing_nullable=True)
    op.alter_column('corrections', 'created_by',
            existing_type=sa.INTEGER(),
            comment=None,
            existing_comment='Создатель коррекции',
            existing_nullable=False)
    op.alter_column('corrections', 'completed_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment=None,
            existing_comment='Фактическая дата выполнения',
            existing_nullable=True)
    op.alter_column('corrections', 'planned_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment=None,
            existing_comment='Плановый срок выполнения',
            existing_nullable=True)
    op.alter_column('corrections', 'corrective_action',
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment='Фактически выполненные действия',
            existing_nullable=False)
    op.alter_column('corrections', 'description',
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment='Описание отклонения/проблемы',
            existing_nullable=True)
    op.alter_column('corrections', 'title',
            existing_type=sa.VARCHAR(length=200),
            comment=None,
            existing_comment='Краткое название корректирующего действия',
            existing_nullable=False)
    op.create_table('root_causes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cause_code_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cause_code_id'], ['cause_codes.id'], name=op.f('root_causes_cause_code_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('root_causes_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('root_causes_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('root_causes_pkey')),
    sa.UniqueConstraint('document_id', name=op.f('root_causes_document_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_root_causes_id'), 'root_causes', ['id'], unique=False)
    # ### end Alembic commands ###
