"""add_name_to_chats

Revision ID: d05e9b16f4b5
Revises: 91adc9e7fda0
Create Date: 2026-04-08 16:03:11.726084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05e9b16f4b5'
down_revision: Union[str, None] = '91adc9e7fda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
