"""remove nonconformity and corrective action tables

Revision ID: d646bdd03be3
Revises: 5a7b62eeeda6
Create Date: 2026-04-06 14:33:23.956467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd646bdd03be3'
down_revision: Union[str, None] = '5a7b62eeeda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonconformity_reports')
    op.drop_table('corrective_actions')
    op.drop_table('nonconformity_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonconformity_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['documents.id'], name=op.f('nonconformity_analyses_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nonconformity_analyses_pkey'))
    )
    op.create_table('corrective_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['documents.id'], name=op.f('corrective_actions_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('corrective_actions_pkey'))
    )
    op.create_table('nonconformity_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['documents.id'], name=op.f('nonconformity_reports_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nonconformity_reports_pkey'))
    )
    # ### end Alembic commands ###
