"""add nonconformity and corrective action tables

Revision ID: d9c7d7cc049c
Revises: 3a1703dcfced
Create Date: 2026-04-06 11:58:21.039812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c7d7cc049c'
down_revision: Union[str, None] = '3a1703dcfced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nonconformity_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyzed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nonconformity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonconformity_reports')
    op.drop_table('nonconformity_analyses')
    op.drop_table('corrective_actions')
    # ### end Alembic commands ###
