"""simplify report models to pk only

Revision ID: f9d1ebc7fac2
Revises: d9c7d7cc049c
Create Date: 2026-04-06 12:01:54.230042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d1ebc7fac2'
down_revision: Union[str, None] = 'd9c7d7cc049c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('corrective_actions_responsible_id_fkey'), 'corrective_actions', type_='foreignkey')
    op.drop_column('corrective_actions', 'deadline')
    op.drop_column('corrective_actions', 'responsible_id')
    op.drop_column('corrective_actions', 'completed_at')
    op.drop_column('corrective_actions', 'action_plan')
    op.drop_constraint(op.f('nonconformity_analyses_analyzed_by_fkey'), 'nonconformity_analyses', type_='foreignkey')
    op.drop_column('nonconformity_analyses', 'root_cause')
    op.drop_column('nonconformity_analyses', 'analyzed_by')
    op.drop_column('nonconformity_analyses', 'impact_assessment')
    op.drop_column('nonconformity_analyses', 'analyzed_at')
    op.drop_constraint(op.f('nonconformity_reports_detected_by_fkey'), 'nonconformity_reports', type_='foreignkey')
    op.drop_column('nonconformity_reports', 'detected_at')
    op.drop_column('nonconformity_reports', 'description')
    op.drop_column('nonconformity_reports', 'detected_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nonconformity_reports', sa.Column('detected_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nonconformity_reports', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nonconformity_reports', sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('nonconformity_reports_detected_by_fkey'), 'nonconformity_reports', 'users', ['detected_by'], ['id'], ondelete='SET NULL')
    op.add_column('nonconformity_analyses', sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('nonconformity_analyses', sa.Column('impact_assessment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nonconformity_analyses', sa.Column('analyzed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nonconformity_analyses', sa.Column('root_cause', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('nonconformity_analyses_analyzed_by_fkey'), 'nonconformity_analyses', 'users', ['analyzed_by'], ['id'], ondelete='SET NULL')
    op.add_column('corrective_actions', sa.Column('action_plan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('corrective_actions', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('corrective_actions', sa.Column('responsible_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('corrective_actions', sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('corrective_actions_responsible_id_fkey'), 'corrective_actions', 'users', ['responsible_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
